const TRAINERS = [
  { nome: "Ash Ketchum" },
  { nome: "Misty" },
  { nome: "Brock" },
  { nome: "Gary Oak" },
  { nome: "Tracey Sketchit" },
  { nome: "May" },
  { nome: "Max" },
  { nome: "Dawn" },
  { nome: "Iris" },
  { nome: "Cilan" },
  { nome: "Serena" },
  { nome: "Clemont" },
  { nome: "Bonnie" },
  { nome: "Lillie" },
  { nome: "Kiawe" },
  { nome: "Mallow" },
  { nome: "Lana" },
  { nome: "Sophocles" },
  { nome: "Goh" },
  { nome: "Chloe" },
  { nome: "Red" },
  { nome: "Blue" },
  { nome: "Green" },
  { nome: "Yellow" },
  { nome: "Gold" },
  { nome: "Silver" },
  { nome: "Crystal" },
  { nome: "Ruby" },
  { nome: "Sapphire" },
  { nome: "Emerald" },
  { nome: "Diamond" },
  { nome: "Pearl" },
  { nome: "Platinum" },
  { nome: "Black" },
  { nome: "White" },
  { nome: "Cheren" },
  { nome: "Bianca" },
  { nome: "N" },
  { nome: "Hugh" },
  { nome: "Calem" },
  { nome: "Serena (Kalos)" },
  { nome: "Shauna" },
  { nome: "Tierno" },
  { nome: "Trevor" },
  { nome: "Elio" },
  { nome: "Selene" },
  { nome: "Victor" },
  { nome: "Gloria" },
  { nome: "Nemona" },
  { nome: "Juliana" },
  { nome: "Florian" },
  { nome: "Professor Oak" },
  { nome: "Professor Elm" },
  { nome: "Professor Birch" },
  { nome: "Professor Rowan" },
  { nome: "Professor Juniper" },
  { nome: "Professor Sycamore" },
  { nome: "Professor Kukui" },
  { nome: "Professor Magnolia" },
  { nome: "Professor Turo" },
  { nome: "Professor Sada" },
  { nome: "Giovanni" },
  { nome: "Lance" },
  { nome: "Steven Stone" },
  { nome: "Wallace" },
  { nome: "Cynthia" },
  { nome: "Alder" },
  { nome: "Iris (Campeã)" },
  { nome: "Diantha" },
  { nome: "Kukui (Masked Royal)" },
  { nome: "Leon" },
  { nome: "Geeta" },
  { nome: "Penny" },
  { nome: "Arven" },
  { nome: "Clavell" },
  { nome: "Miriam" },
  { nome: "Grusha" },
  { nome: "Brassius" },
  { nome: "Iono" },
  { nome: "Kofu" },
  { nome: "Larry" },
  { nome: "Ryme" },
  { nome: "Tulip" },
  { nome: "Hassel" },
  { nome: "Palmer" },
  { nome: "Argenta" },
  { nome: "Thorton" },
  { nome: "Dara" },
  { nome: "Riley" },
  { nome: "Marley" },
  { nome: "Buck" },
  { nome: "Mira" },
  { nome: "Aaron" },
  { nome: "Bertha" },
  { nome: "Flint" },
  { nome: "Lucian" },
  { nome: "Blaine" },
  { nome: "Sabrina" },
  { nome: "Erika" },
  { nome: "Lt. Surge" },
  { nome: "Koga" },
  { nome: "Janine" },
  { nome: "Falkner" },
  { nome: "Bugsy" },
  { nome: "Whitney" },
  { nome: "Morty" },
  { nome: "Chuck" },
  { nome: "Jasmine" },
  { nome: "Pryce" },
  { nome: "Clair" },
  { nome: "Roxanne" },
  { nome: "Brawly" },
  { nome: "Wattson" },
  { nome: "Flannery" },
  { nome: "Norman" },
  { nome: "Winona" },
  { nome: "Tate" },
  { nome: "Liza" },
  { nome: "Juan" },
  { nome: "Roark" },
  { nome: "Gardenia" },
  { nome: "Maylene" },
  { nome: "Crasher Wake" },
  { nome: "Fantina" },
  { nome: "Byron" },
  { nome: "Candice" },
  { nome: "Volkner" },
  { nome: "Chili" },
  { nome: "Cress" },
  { nome: "Elesa" },
  { nome: "Clay" },
  { nome: "Skyla" },
  { nome: "Drayden" },
  { nome: "Marlon" },
  { nome: "Viola" },
  { nome: "Grant" },
  { nome: "Korrina" },
  { nome: "Valerie" },
  { nome: "Olympia" },
  { nome: "Wulfric" },
  { nome: "Milo" },
  { nome: "Nessa" },
  { nome: "Bea" },
  { nome: "Opal" },
  { nome: "Piers" },
  { nome: "Raihan" },
];

export default TRAINERS;
