import { ColorModeScript } from "@chakra-ui/react"; // ✅ Importa aqui
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Providers from "./providers";
import { HStack } from "@chakra-ui/react";
import theme from "@/theme"; // ✅ Importa o tema aqui também

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body>

        <Providers>
          <HStack w="100vw" h="100vh" gap="0">
            <Sidebar />
            {children}
          </HStack>
        </Providers>
      </body>
    </html>
  );
}
