import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import Sidebar from "@/components/Sidebar";
import { HStack } from "@chakra-ui/react";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body className={`${montserrat.variable}`}>
        <Provider>
          <HStack w="100vw" h="100vh" gap="0">
            <Sidebar />
            {children}
          </HStack>
        </Provider>
      </body>
    </html>
  );
}
